version = 1

[[annotations]]
path = "bom/*.csv"
SPDX-FileCopyrightText = "© 2025 Mekanika SRL"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "cad/*.step"
SPDX-FileCopyrightText = "© 2025 Mekanika SRL"
SPDX-License-Identifier = "CERN-OHL-S-2.0"

[[annotations]]
path = "docs/*.md, docs/*.qet"
SPDX-FileCopyrightText = "© 2025 Mekanika SRL"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "LICENSES/*.txt"
SPDX-FileCopyrightText = "© 2025 Mekanika SRL"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "© 2025 Mekanika SRL"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "REUSE.toml"
SPDX-FileCopyrightText = "© 2025 Mekanika SRL"
SPDX-License-Identifier = "CC-BY-SA-4.0"
